### PR TITLE
Use Homebrew's License

### PR DESCRIPTION
**Pull request by adzenith**

### CODE REVIEW

**Comment by nitsky** [comment]
thanks, what needs to be done to get this into homebrew?

**Comment by adzenith** [comment]
Depends if you want to keep the history or not. If you don't, pretty much just fork the Homebrew repo, add the formula, then send a PR. More [here](https://github.com/Homebrew/homebrew/blob/master/CONTRIBUTING.md). I'm more than happy to do it, but you might want to do it if you want your name on the PR.

If you want to keep the history... that'll be more complicated. I'd chop up the repo using `filter-branch`, and reword commits so that they all start with `arm-none-eabi-gcc:`. Then you could rebase onto Homebrew's repo and send a PR.

**Comment by nitsky** [comment]
submitted a PR, https://github.com/Homebrew/homebrew/pull/45236

**Comment by adzenith** [comment]
Well, that went well.

**Comment by nitsky** [comment]
No prob, thanks!

**Pull request merged**
